nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

readarr:
  annotations: {}
  replicas: 1
  strategyType: Recreate
  image:
    repository: lscr.io/linuxserver/readarr
    tag: ""
  securityContext:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: ""
  env: []
  envFrom: []
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 10
    tcpSocket:
      port: 8787
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 10
    tcpSocket:
      port: 8787
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 30
    periodSeconds: 5
    tcpSocket:
      port: 8787
    timeoutSeconds: 1

service:
  annotations: {}
  ports:
    - name: http
      port: 8787
      protocol: TCP
  type: ClusterIP

ingress:
  enabled: false
  annotations: {}
  mainPort: 8787
  ingressClassName: ""
  hosts: []
  tls: []

config:
  annotations: {}
  enabled: true
  existingClaim: ""
  size: "1Gi"
  accessMode: ReadWriteOnce
  retain: false

books:
  annotations: {}
  enabled: true
  existingClaim: ""
  size: "50Gi"
  accessMode: ReadWriteMany
  retain: false
