# -- Optional short name override for the resources
nameOverride: ""
# -- Optional full name override for the resources
fullnameOverride: ""

blocky:
  # -- Annotations to apply to the Blocky pod
  annotations: {}
  # -- How many replicas of the Blocky pod to run
  replicas: 2
  # -- The strategy to use for updating the Blocky pods
  strategyType: RollingUpdate
  image:
    # -- The image repository to pull from
    repository: ghcr.io/0xerr0r/blocky
    # -- The image tag to pull
    tag: ""
  securityContext:
    # -- Whether to run Blocky with a read-only root filesystem
    readOnlyRootFilesystem: true
    # -- The user ID to run Blocky as
    runAsUser: 1000
  resources:
    requests:
      # -- The amount of memory to request for the Blocky pod
      memory: "128Mi"
      # -- The amount of CPU to request for the Blocky pod
      cpu: "100m"
    limits:
      # -- The amount of memory to limit the Blocky pod to
      memory: "128Mi"
      # -- The amount of CPU to limit the Blocky pod to
      cpu: ""
  # -- Whether to enable or disable recommended podAntiAffinity rules
  podAntiAffinity: true

service:
  # -- Annotations to apply to the Blocky service
  annotations: {}
  # -- Port to expose the Blocky service on
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: http
      port: 4000
      protocol: TCP
  # -- The type of service to create
  type: LoadBalancer

config:
  # -- Annotations to apply to the Blocky ConfigMap
  annotations: {}
  # -- The configuration for Blocky
  yaml: |
    upstream:
      default:
        - 1.1.1.1
        - 8.8.8.8
    blocking:
      blackLists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - ads
    port: 53
    httpPort: 4000
    caching:
      minTime: 5m
      maxTime: 30m
