apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowlarr.fullname" . }}
  namespace: {{ include "prowlarr.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "prowlarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "prowlarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.service.ports }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
    {{- end }}
  {{- end }}
  type: {{ .Values.service.type }}
