apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "blocky.fullname" .) }}
  namespace: {{ include "blocky.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "blocky.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.config.annotations }}
  annotations:
    {{- toYaml .Values.config.annotations | nindent 4 }}
  {{- end }}
data:
  config.yml: |
    {{- .Values.config.yaml | nindent 4 }}
