apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocky.fullname" . }}-config
  namespace: {{ include "blocky.namespace" . }}
  {{- if .Values.config.annotations }}
  annotations:
    {{- toYaml .Values.config.annotations | nindent 4 }}
  {{- end }}
data:
  config.yml: |
    {{- .Values.config.yaml | nindent 4 }}
