apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blocky.fullname" . }}
  namespace: {{ include "blocky.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "blocky.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.blocky.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blocky.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.blocky.strategyType }}
  strategy:
    type: {{ .Values.blocky.strategyType }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "blocky.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.blocky.annotations }}
      annotations:
        {{- toYaml .Values.blocky.annotations | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.blocky.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "blocky.name" . }}
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- end }}
      containers:
        - name: blocky
          image: "{{ .Values.blocky.image.repository }}:{{ include "blocky.image" . }}"
          {{- if .Values.blocky.resources }}
          resources:
            {{- if .Values.blocky.resources.requests }}
            requests:
              {{- if .Values.blocky.resources.requests.memory }}
              memory: "{{ .Values.blocky.resources.requests.memory }}"
              {{- end }}
              {{- if .Values.blocky.resources.requests.cpu }}
              cpu: "{{ .Values.blocky.resources.requests.cpu }}"
              {{- end }}
            {{- end }}
            {{- if .Values.blocky.resources.limits }}
            limits:
              {{- if .Values.blocky.resources.limits.memory }}
              memory: "{{ .Values.blocky.resources.limits.memory }}"
              {{- end }}
              {{- if .Values.blocky.resources.limits.cpu }}
              cpu: "{{ .Values.blocky.resources.limits.cpu }}"
              {{- end }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
          {{- if .Values.blocky.securityContext }}
          securityContext:
            {{- toYaml .Values.blocky.securityContext | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "blocky.fullname" . }}-config
