{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blocky.fullname" . }}
  namespace: {{ include "blocky.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "blocky.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.metrics.annotations }}
  annotations:
    {{- toYaml .Values.metrics.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: {{ .Values.metrics.port }}
      {{- if .Values.metrics.interval }}
      interval: {{ .Values.metrics.interval }}
      {{- end }}
      {{- if .Values.metrics.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
      {{- end }}
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blocky.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ include "blocky.namespace" . }}
{{- end }}
