# -- Optional short name override for the resources
nameOverride: ""
# -- Optional full name override for the resources
fullnameOverride: ""
# -- Optional namespace override for the resources
namespaceOverride: ""

radarr:
  # -- Annotations to apply to the Radarr pod
  annotations: {}
  # -- How many replicas of the Radarr pod to run
  replicas: 1
  # -- The strategy to use for updating the Radarr pods
  strategyType: Recreate
  image:
    # -- The image repository to pull from
    repository: lscr.io/linuxserver/radarr
    # -- The image tag to pull
    tag: ""
  securityContext:
    # -- Whether to run Radarr with a read-only root filesystem
    readOnlyRootFilesystem: false
    # -- The user ID to run Radarr as
    runAsUser: 0
    # -- The group ID to run Prowlarr as
    runAsGroup: 0
  resources:
    requests:
      # -- The amount of memory to request for the Radarr pod
      memory: "512Mi"
      # -- The amount of CPU to request for the Radarr pod
      cpu: "50m"
    limits:
      # -- The amount of memory to limit the Radarr pod to
      memory: "512Mi"
      # -- The amount of CPU to limit the Radarr pod to
      cpu: ""
  # -- The environment variables to set for the Radarr pod
  env: []
  # -- The livenessProbe configuration for the Radarr pod
  livenessProbe:
    exec:
      command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> &&
          while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi;
          done < /config/config.xml`
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  # -- The readinessProbe configuration for the Radarr pod
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    tcpSocket:
      port: 7878
    timeoutSeconds: 1
  # -- The startupProbe configuration for the Radarr pod
  startupProbe:
    failureThreshold: 30
    initialDelaySeconds: 0
    periodSeconds: 5
    tcpSocket:
      port: 7878
    timeoutSeconds: 1

service:
  # -- Annotations to apply to the Radarr service
  annotations: {}
  # -- Port to expose the Radarr service on
  ports:
    - name: http
      port: 7878
      protocol: TCP
  # -- The type of service to create
  type: ClusterIP

ingress:
  # -- Whether to create an ingress for Radarr
  enabled: false
  # -- Annotations to apply to the Radarr ingress
  annotations: {}
  # -- The main http port to use for the Radarr ingress
  mainPort: 7878
  # -- The ingress class to use for the Radarr ingress
  ingressClassName: ""
  # -- Host configuration for the Radarr ingress
  hosts: []
  #   - host: radarr.example.com
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # -- TLS configuration for the Radarr ingress
  tls: []
  #   - hosts:
  #       - radarr.example.com
  #     secretName: radarr-ingress-tls

config:
  # -- Annotations to apply to the Radarr config persistent volume claim
  annotations: {}
  # -- Whether to enable the creation of a persistent volume claim for the Radarr config
  enabled: true
  # -- Use this attribute to reference an existing persistent volume claim to use for the Radarr config
  existingClaim: ""
  # -- The amount of storage to request for the Radarr config
  size: "1Gi"
  # -- The access mode to use for the Radarr config persistent volume claim
  accessMode: ReadWriteOnce
  # -- Whether to keep the persistent volume claim for the config after the Radarr chart is uninstalled
  retain: false

media:
  # -- Annotations to apply to the Radarr media persistent volume claim
  annotations: {}
  # -- Whether to enable the creation of a persistent volume claim for the Radarr media
  enabled: true
  # -- Use this attribute to reference an existing persistent volume claim to use for the Radarr media
  existingClaim: ""
  # -- The amount of storage to request for the Radarr media
  size: "50Gi"
  # -- The access mode to use for the Radarr media persistent volume claim
  accessMode: ReadWriteOnce
  # -- Whether to keep the persistent volume claim for the media after the Radarr chart is uninstalled
  retain: false
