{{- if and .Values.media.enabled (not .Values.media.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "bazarr.mediaClaimName" . }}
  namespace: {{ include "bazarr.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "bazarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with (include "bazarr.mediaAnnotations" .) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.media.accessMode }}
  resources:
    requests:
      storage: {{ .Values.media.size }}
{{- end }}
