{{- if and .Values.books.enabled (not .Values.books.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "readarr.booksClaimName" . }}
  namespace: {{ include "readarr.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "readarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with (include "readarr.booksAnnotations" .) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.books.accessMode }}
  resources:
    requests:
      storage: {{ .Values.books.size }}
{{- end }}
