name: Pull request

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write
  repository-projects: read

jobs:
  test-and-build:
    strategy:
      matrix:
        chart: [bazarr, blocky, prowlarr, radarr, sonarr]
    name: Test (${{ matrix.chart }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for changed files
        uses: dorny/paths-filter@v3
        id: changed-files
        with:
          filters: |
            chart:
              - 'charts/${{ matrix.chart }}/**'
      - name: Verify labels
        uses: Brains-Beyond-Expectations/labeller@v1
        if: steps.changed-files.outputs.chart == 'true'
        with:
          add_labels: ${{ matrix.chart }}
          required_labels: |
            feature,enhancement,fix,bugfix,bug,chore
            major,minor,patch
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        if: steps.changed-files.outputs.chart == 'true'
      - name: Set up Helm
        uses: azure/setup-helm@v4
        if: steps.changed-files.outputs.chart == 'true'
      - name: Install Helm unittest plugin
        if: steps.changed-files.outputs.chart == 'true'
        run:
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - name: Run unit tests
        if: steps.changed-files.outputs.chart == 'true'
        working-directory: charts/${{ matrix.chart }}
        run: |
          helm dependency update
          helm unittest .
      - name: Render chart
        if: steps.changed-files.outputs.chart == 'true'
        working-directory: charts/${{ matrix.chart }}
        run: |
          helm template . --values tests/values/required-values.yaml --output-dir /tmp/${{ matrix.chart }}
      - name: Lint chart
        if: steps.changed-files.outputs.chart == 'true'
        uses: stackrox/kube-linter-action@v1
        with:
          directory: /tmp/${{ matrix.chart }}
          config: charts/${{ matrix.chart }}/.kube-linter.yaml
